using System;
using System.Collections.Generic;
using YargArchipelagoPlugin;
using static YargArchipelagoCommon.CommonData;

namespace Yaml_Creator
{
    public class YAMLCore
    {
        public string name = "";
        public string description = $"YAML generated by YAYARG Yaml Creator V{ArchipelagoPlugin.pluginVersion}";
        public string game = "YAYARG";
        public YARGSettings YAYARG = new YARGSettings();
    }
    public class YARGSettings
    {
        public int progression_balancing = 50;
        public string accessibility = "full";
        public string songList = "";
        public Dictionary<string, SongPool> song_pools = new Dictionary<string, SongPool>();
        public HashSet<string> song_exclusion_list = new HashSet<string>();
        public Dictionary<string, string[]> exclusions_per_pool = new Dictionary<string, string[]>();
        public Dictionary<string, string[]> inclusions_per_pool = new Dictionary<string, string[]>();
        public string goal_pool_plando = string.Empty;
        public string goal_song_plando = string.Empty;
        public int song_check_extra = 100;
        public int song_pack_size = 1;
        public bool instrument_shuffle = false;
        public bool reuse_songs = false;
        public int starting_songs = 3;
        public bool goal_song_item_needed = false;
        public int setlist_needed = 80;
        public int fame_point_needed = 80;
        public int fame_point_amount = 30;
        public int star_power = 5;
        public int swap_song_random = 3;
        public int swap_song_choice = 1;
        public int lower_difficulty = 1;
        public int restart_trap = 0;
        public int rock_meter_trap = 2;
        public int nothing = 0;
        public int fail_prevention = 0;
        public DeathLinkType death_link = DeathLinkType.disabled;
        public EnergyLinkType energy_link = EnergyLinkType.any_song;
    }
}
